### ISSUE TITLE
Remove jnuma dependency

### ISSUE THREAD

**Issue by kuenishi** [retz/retz#10]
~~Although we need NUMA awareness and jnuma is great,  one test on CPUManager are tentatively failing in Wercker CI~~. We need portability on such containers, additionally FreeBSD and MacOS ^^;

**Comment by shino** [comment]
CPUManagerTest failure was by another reason. jnuma is totally not bad and does nice job.

**Comment by kuenishi** [comment]
fb0ed96448668c78a25719
