### ISSUE TITLE
allow to set shutdown grace period during kill

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#100]
Mesos allows to set the period between SIGTERM and SIGKILL when killing a task (cf. https://issues.apache.org/jira/browse/MESOS-1773), but by default (3s for me?) this period is too short for some graceful shutdown tasks. It would be nice to be able to set this period for Retz applications.

**Comment by kuenishi** [comment]
https://github.com/retz/retz/commit/0e18aef451aec0f8a8972a89d87eff983981c358 should be working IMHC (in my horrible code).

**Comment by tgpfeiffer** [comment]
This works great, thank you!
