### ISSUE TITLE
Retz should automatically find leader in multi-master setup

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#140]
At the moment, in a setup with multiple masters who elect a leader via Zookeeper, if the host set in `retz.mesos` is not currently the leader, then Retz will neither output an error message nor re-connect to the current leader. Retz will output

> 2017-03-28 11:42:18.771 INFO  [main] io.github.retz.scheduler.Launcher - Connecting to Mesos master mesos1:5050 as nobody

but never arrive at the point where it outputs

> 2017-03-28 11:52:09.527 INFO  [Thread-2] i.g.retz.scheduler.RetzScheduler - Connected to master mesos3; Framework ID: 6126772b-3a46-478c-b1ef-5b0585e73a16-0001

However, in particular in a high-availability setup, Retz should be able to find the current leader automatically, or at least output a message that the specified host is not the leader.

**Comment by kuenishi** [comment]
In my local setup with three Mesos masters, setting `retz.mesos = zk://zk1:2181,zk2:2181,zk3:2181/mesos` in `/opt/retz-server/etc/retz.properties` worked for me - Mesos client inside Retz automatically followed Mesos master failover ... with an exception in fetching files in the task sandbox. I'll fix it soon, but without `get-file` and `run` subcommand it should work. Please let me know if any other part is not working.

**Comment by kuenishi** [comment]
With 0.2.10 this should be fixed. Feel free to reopen if any further issues.
