### ISSUE TITLE
Retz should survive leader change

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#141]
Related to #140: If the leader changes in a HA environment, Retz does not follow that leader change. While it continues to run (without receiving any offers, of course), it disappears from the Mesos web interface as a framework. Instead it should detect the leader change and continue as a framework with the new leader.

**Comment by kuenishi** [comment]
As I commented in #140, Mesos client automatically reconnects to the new master after leader change. Please check the documentation I just have updated ( 70bba684e1e40453019e5339a08a122118f1aede ) for how.

**Comment by kuenishi** [comment]
With 0.2.10 this should be fixed. Feel free to reopen if any further issues.
