### ISSUE TITLE
add tasks arguments

### ISSUE THREAD

**Issue by vixns** [retz/retz#42]
like mesos-execute, allow to pass volumes, networks, env and resources to tasks.

**Comment by kuenishi** [comment]
Retz is able to create volumes for each registered application with application-specific name. Also, you can give environment variables with `-E` option to `schedule` and `run` subcommands. Resources are slightly different from general Mesos style like `cpus:1;gpus:2;` but its capable with `-cpu 1 -gpu 2` style options.

Networks are not supported yet.
