### ISSUE TITLE
Get rid of RetzExecutor

### ISSUE THREAD

**Issue by kuenishi** [retz/retz#49]
Original purpose of RetzExecutor was to control CPU affinity for AsakusaFW on M3BP, manage files in persistent volumes in our way. But CPU affinity control is an early optimization and basically it must cooperate with Mesos itself. Also, managing persistent volumes for caching large files is not at good tradeoff between performance, fault tolerance and usability, and few need to use - I'm going to deprecate it so far.

[It also resolves an issue for high availability](https://www.mail-archive.com/user@mesos.apache.org/msg08148.html).

**Comment by ashigeru** [comment]
👍

**Comment by kuenishi** [comment]
Use it as non-Mesos mode backend running locally.

**Comment by kuenishi** [comment]
RIP https://github.com/retz/retz/commit/d1d313e692ae694f9c66c46d607b90f81612f0ed
