### ISSUE TITLE
retz.bind on server listens on more interfaces than specified

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#62]
`retz.bind` on the client side specifies the location of the Retz server. `retz.bind` on the server side specifies the interface to listen on. However, even when `http://localhost:9090` is specified, the server does not listen only on the loopback device, but on all devices. (The usual syntax employed by many programs to say "listen on all interfaces" would be `0.0.0.0:9090`, but in combination with the `http://` prefix is very weird.)

**Comment by kuenishi** [comment]
Thank you for pointing out this issue. This stems from the limitation of [web framework Sparkjava](http://sparkjava.com/) which only can listen `0.0.0.0`, plus using same configuration name at both server and client. This would be another +1 reason to move onto other web framework ( #45 ).  I'd even want to prohibit listening to `0.0.0.0`.

**Comment by tgpfeiffer** [comment]
Note that specifying "http://localhost:9090" is also a problem because the link to the Retz web interface from the Mesos web interface will then point to "http://localhost:9090".

**Comment by kuenishi** [comment]
This is mostly solved by https://github.com/retz/retz/commit/d760322b5c60314aa5abbc01d3ace58f02c53d36 . We'll need another commit to warn binding to loopback address.

**Comment by kuenishi** [comment]
This is finally fixed at https://github.com/retz/retz/commit/843ac0b00ddcad89866d065d0ba321a1c711bed7  . I wasn't aware of `spark.Spark.ipAddress(String)` which is quite oops.

**Comment by kuenishi** [comment]
For test conveniecne, it still allows binding loopback address.

**Comment by tgpfeiffer** [comment]
I checked that `http://localhost:9090` does still work (which is good, I think) and that `http://0.0.0.0:9090` does not work and that the retz server binds only to the specified IP address.
