### ISSUE TITLE
allow to specify a number of ports as resource request

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#65]
Sometimes the user may want to launch a task that opens network ports. Therefore it should be possible for the Retz user to also specify a number of ports that the task wants to use. It must then be possible (1) for the app to look up which ports have been assigned (e.g., via an environment variable) and (2) for the user to look up the same (e.g., via a column in the `retz-client list` output).

**Comment by kuenishi** [comment]
https://github.com/retz/retz/commit/c1fe39c998fdb433d65fde0f4f70bb27eaf3ed0b . (1) Allocated ports are to be told to application as environment variables like `$PORT0`, `$PORT(n)`  as Marathon does. (2) They'll also be printed to `stdout` so users may see them by `get-file` command. Further tests may be needed, but I'll close this for now. Feel free to add further requests here with comment or a new issue.
