### ISSUE TITLE
dpkg installation error when retz user already exists

### ISSUE THREAD

**Issue by akirakw** [retz/retz#67]
When I tried to install retz-server with dpkg ( retz-server_0.0.29_amd64.deb ) on retz user, I recieved installation error with "failed to create retz user" and deb package system of my environment has become inconsistent - cannot re-install and uninstall any packages.

**Comment by kuenishi** [comment]
Plus: Retz installer (RPM and DEB) overwrites `retz.properties` with new one; while it must preserve old config file.

**Comment by kuenishi** [comment]
1c33276e6b20348ef3d
