### ISSUE TITLE
date formatter in list-files is broken

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#78]
In https://github.com/retz/retz/blob/d760322b5c60314aa5abbc01d3ace58f02c53d36/retz-client/src/main/java/io/github/retz/cli/CommandListFiles.java#L79 various formatting placeholders in SimpleDateFormat are not correct (e.g. `m` vs `M`).

**Comment by kuenishi** [comment]
`2016-15-11 05:15:36` was quite wrong. Fixed by https://github.com/retz/retz/commit/099ef9db279888a16335f26e2e848857a5614cb3. Thank you for reporting such a stupid bug!
