### ISSUE TITLE
killing a non-existing job returns HTTP 500

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#83]
Killing a job that does not exist does not return a proper "job does not exist" message with a 404 code, but the server returns HTTP 500 response:

```
$ ./bin/retz-client -C retz.properties kill -id 40
...
[main] INFO io.github.retz.cli.CommandKill - Killing job detail id=40
[main] ERROR io.github.retz.cli.CommandKill - Error: java.io.IOException: Server returned HTTP response code: 500 for URL: http://mesos3:9090/job/40
```

In particular for consumers of the Retz API, it is at the moment not possible to check whether the job was not present (which is not an exceptional situation) or whether there was really some internal error.

**Comment by kuenishi** [comment]
https://github.com/retz/retz/commit/73c9765f75db9079b7f97ab829ce1f609131a79d . Other cases like application not found would be another issue
