### ISSUE TITLE
jobs with requested `ports` resources are not started

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#84]
When I start a job with `./bin/retz-client -C retz.properties run -A foo -cmd "hostname"` it is executed immediately and the hostname is printed to the console. When I add `-ports 1`, the last log line is

    [main] INFO io.github.retz.cli.CommandRun - job 26 scheduled

and the job hangs there forever.

Related to #65

**Comment by kuenishi** [comment]
This is not reproducible in my single-node VM environment, both on vanilla process and under Docker image, at git head `099ef9db279888a16` . Could you elaborate more about your environment and procedure? (private messaging or other media is also fine if you can't disclose publicly)

**Comment by tgpfeiffer** [comment]
OK, sorry, this may be caused by my local hack to work around #74. Please ignore this for now, I'll revisit this when #74 is fixed.

**Comment by kuenishi** [comment]
This was reproduced in my two-nodes VM environment, and root cause was same as #74 but exception was hidden behind ExecutionService. Visibility fix https://github.com/retz/retz/commit/951a47b66baa737ccaff7f6a7f910bed8d80e6a3 is also included in 0.0.32.

**Comment by tgpfeiffer** [comment]
Confirmed to be fixed in 0.0.33-SNAPSHOT (and as you said, most probably already in 0.0.32).
