### ISSUE TITLE
inconsistency in command line parameters

### ISSUE THREAD

**Issue by tgpfeiffer** [retz/retz#98]
It is hard to memorize the command line parameters correctly because they do not always follow the conventions of being either `-x` or `--xlong`, for example:

```
Usage: list-files(List files in the sandbox of a job) [options]
  Options:
    --path
      Remote sandbox path to list
      Default: $MESOS_SANDBOX
  * -id
      Job ID whose state and details you want
      Default: 0
```

**Comment by kuenishi** [comment]
https://github.com/retz/retz/commit/b5ff655183b31e684e89365f345c051d97470684 will be in 0.1.2

**Comment by kuenishi** [comment]
0.1.2 was released. Feel free to reopen if any further issues related to this.
